import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter_application_1/app/widgets/pressable.dart';
import 'package:flutter_application_1/l10n/app_localizations.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

import 'package:go_router/go_router.dart';
import 'package:flutter_application_1/app/bloc/notes/notes_bloc.dart';
import 'package:flutter_application_1/app/bloc/notes/notes_event.dart';
import 'package:flutter_application_1/app/bloc/notes/notes_state.dart';
import 'package:flutter_application_1/data/helpers/di/injector.dart';
import 'package:flutter_application_1/data/models/notes_model.dart';
import 'package:flutter_application_1/data/models/task_model.dart';
import 'package:image_picker/image_picker.dart';

class AddNotePage extends StatefulWidget {
  const AddNotePage({super.key});

  @override
  State<AddNotePage> createState() => _AddNotePageState();
}

class _AddNotePageState extends State<AddNotePage> {
  final _titleController = TextEditingController();
  final _contentController = TextEditingController();
  final List<TaskModel> _tasks = [];
  final _taskController = TextEditingController();
  final ImagePicker _imagePicker = ImagePicker();
  final List<XFile> _pickedImages = [];
  String _selectedTag = '';

  @override
  void dispose() {
    _titleController.dispose();
    _contentController.dispose();
    _taskController.dispose();
    super.dispose();
  }

  void _addTask() {
    if (_taskController.text.trim().isEmpty) return;
    setState(() {
      _tasks.add(TaskModel(
        id: DateTime.now().millisecondsSinceEpoch.toString(),
        text: _taskController.text.trim(),
        done: false,
      ));
      _taskController.clear();
    });
  }

  void _removeTask(int index) {
    setState(() {
      _tasks.removeAt(index);
    });
  }

  Future<void> _pickFromGallery() async {
    try {
      final images = await _imagePicker.pickMultiImage();
      if (images.isEmpty) return;
      setState(() {
        _pickedImages.addAll(images);
      });
    } catch (e) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Failed to pick images: $e')),
      );
    }
  }

  Future<void> _captureImage() async {
    try {
      final image = await _imagePicker.pickImage(source: ImageSource.camera);
      if (image == null) return;
      setState(() {
        _pickedImages.add(image);
      });
    } catch (e) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Failed to capture image: $e')),
      );
    }
  }

  void _removeImage(int index) {
    setState(() {
      _pickedImages.removeAt(index);
    });
  }

  void _saveNote(BuildContext context) {
    if (_titleController.text.isEmpty && _contentController.text.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Title or content cannot be empty'),backgroundColor: Colors.red, ),
      );
      return;
    }

    final note = NoteModel(
      id: '', // ID will be generated by Firestore
      title: _titleController.text.trim(),
      content: _contentController.text.trim(),
      tasks: List<TaskModel>.from(_tasks),
      tags: _selectedTag.isNotEmpty ? [_selectedTag] : [],
      pinned: false,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    );

    final attachmentPaths = _pickedImages.map((image) => image.path).toList();
    context
      .read<NotesBloc>()
      .add(AddNote(note, attachmentPaths: attachmentPaths));
    context.pop();
  }

  @override
  Widget build(BuildContext context) {
    final loc = AppLocalizations.of(context);
    return BlocProvider(
      create: (context) => sl<NotesBloc>(),
      child: BlocConsumer<NotesBloc, NotesState>(
        listener: (context, state) {
          if (state is NotesFailure) {
            ScaffoldMessenger.of(context).showSnackBar(
              SnackBar(content: Text('Error: ${state.error}')),
            );
          }
        },
        builder: (context, state) {
          return Scaffold(
            appBar: AppBar(
              title: Text(loc?.addNote ?? 'Add Note'),
              actions: [
                // InkWell(
                //   child: const Icon(Icons.check),
                //   onTap: () => _saveNote(context),
                // ),
                PressableButton(
                 child: Container(
                    padding: const EdgeInsets.all(8.0),
                    child: const Icon(Icons.check),
                    decoration:  BoxDecoration(
                      color: Colors.blue,
                      borderRadius: BorderRadius.circular(8.0),
                    ),
                 ),
                 onTap: () => _saveNote(context))
              ],
            ),
            body: SingleChildScrollView(
              padding: const EdgeInsets.all(16.0),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  TextField(
                    controller: _titleController,
                    style: Theme.of(context).textTheme.headlineSmall,
                    decoration: const InputDecoration(
                      hintText: 'Title',
                      border: InputBorder.none,
                    ),
                  ),
                  const SizedBox(height: 8),
                  TextField(
                    controller: _contentController,
                    maxLines: null,
                    decoration: const InputDecoration(
                      hintText: 'Note content',
                      border: InputBorder.none,
                    ),
                  ),
                  const SizedBox(height: 20),
                  // const Divider(),
                  Text(loc?.addTask ?? 'Add Task', style: const TextStyle(fontWeight: FontWeight.bold)),
                  ListView.builder(
                    shrinkWrap: true,
                    physics: const NeverScrollableScrollPhysics(),
                    itemCount: _tasks.length,
                    itemBuilder: (context, index) {
                      final task = _tasks[index];
                      return ListTile(
                        contentPadding: EdgeInsets.zero,
                        leading: const Icon(Icons.check_box_outline_blank),
                        title: Text(task.text),
                        trailing: IconButton(
                          icon: const Icon(Icons.close),
                          onPressed: () => _removeTask(index),
                        ),
                      );
                    },
                  ),
                 
                  Row(
                    children: [
                      Expanded(
                        child: TextField(
                          controller: _taskController,
                          decoration: InputDecoration(
                            hintText: loc?.addTask ?? 'Add Task',
                            border: InputBorder.none,
                          ),
                          onSubmitted: (_) => _addTask(),
                        ),
                      ),
                      IconButton(
                        icon: const Icon(Icons.add),
                        onPressed: _addTask,
                      ),
                    ],
                  ),

                  const SizedBox(height: 20),

                  Text(
                    'Tags',
                    style: Theme.of(context).textTheme.titleMedium,
                  ),
                  Wrap(
                       spacing: 8,
                       children: ["work", "personal", "urgent","Scool", "Ideas", "church", "Todo"].map((tag) =>
                        ChoiceChip(
                          selected: _selectedTag == tag,
                          onSelected: (selected) {
                            setState(() {
                              _selectedTag = selected ? tag : '';
                            });
                          
                          },
                          label: Text(tag)))
                          .toList(),
                  ),

                  const SizedBox(height: 24),

                  Text(
                    'Attachments',
                    style: Theme.of(context).textTheme.titleMedium,
                  ),
                  const SizedBox(height: 12),
                  if (_pickedImages.isNotEmpty)
                    Wrap(
                      spacing: 12,
                      runSpacing: 12,
                      children: List.generate(_pickedImages.length, (index) {
                        final file = File(_pickedImages[index].path);
                        return Stack(
                          alignment: Alignment.topRight,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(12),
                              child: Image.file(
                                file,
                                width: 100,
                                height: 100,
                                fit: BoxFit.cover,
                              ),
                            ),
                            Positioned(
                              top: 4,
                              right: 4,
                              child: CircleAvatar(
                                radius: 14,
                                backgroundColor:
                                    Colors.black.withOpacity(0.6),
                                child: IconButton(
                                  padding: EdgeInsets.zero,
                                  icon: const Icon(Icons.close,
                                      size: 16, color: Colors.white),
                                  onPressed: () => _removeImage(index),
                                ),
                              ),
                            ),
                          ],
                        );
                      }),
                    )
                  else
                    Text(
                      'No images attached',
                      style: Theme.of(context)
                          .textTheme
                          .bodyMedium
                          ?.copyWith(color: Colors.grey),
                    ),
                  const SizedBox(height: 12),
                  Row(
                    children: [
                      Expanded(
                        child: OutlinedButton.icon(
                          icon: const Icon(Icons.photo_library_outlined),
                          label: const Text('Gallery'),
                          onPressed: _pickFromGallery,
                        ),
                      ),
                      const SizedBox(width: 12),
                      Expanded(
                        child: OutlinedButton.icon(
                          icon: const Icon(Icons.photo_camera_outlined),
                          label: const Text('Camera'),
                          onPressed: _captureImage,
                        ),
                      ),
                    ],
                  ),
                ],
              ),
            ),
          );
        },
      ),
    );
  }
}