import 'package:flutter/material.dart';
import 'package:flutter_application_1/app/widgets/pressable.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:go_router/go_router.dart';
import 'package:flutter_application_1/app/bloc/notes/notes_bloc.dart';
import 'package:flutter_application_1/app/bloc/notes/notes_event.dart';
import 'package:flutter_application_1/app/bloc/notes/notes_state.dart';
import 'package:flutter_application_1/data/helpers/di/injector.dart';
import 'package:flutter_application_1/data/models/notes_model.dart';
import 'package:flutter_application_1/data/models/task_model.dart';

class AddNotePage extends StatefulWidget {
  const AddNotePage({super.key});

  @override
  State<AddNotePage> createState() => _AddNotePageState();
}

class _AddNotePageState extends State<AddNotePage> {
  final _titleController = TextEditingController();
  final _contentController = TextEditingController();
  final List<TaskModel> _tasks = [];
  final _taskController = TextEditingController();
  String _selectedTag = '';

  @override
  void dispose() {
    _titleController.dispose();
    _contentController.dispose();
    _taskController.dispose();
    super.dispose();
  }

  void _addTask() {
    if (_taskController.text.trim().isEmpty) return;
    setState(() {
      _tasks.add(TaskModel(
        id: DateTime.now().millisecondsSinceEpoch.toString(),
        text: _taskController.text.trim(),
        done: false,
      ));
      _taskController.clear();
    });
  }

  void _removeTask(int index) {
    setState(() {
      _tasks.removeAt(index);
    });
  }

  void _saveNote(BuildContext context) {
    if (_titleController.text.isEmpty && _contentController.text.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Title or content cannot be empty'),backgroundColor: Colors.red, ),
      );
      return;
    }

    final note = NoteModel(
      id: '', // ID will be generated by Firestore
      title: _titleController.text.trim(),
      content: _contentController.text.trim(),
      tasks: List<TaskModel>.from(_tasks),
      tags: _selectedTag.isNotEmpty ? [_selectedTag] : [],
      pinned: false,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    );

    context.read<NotesBloc>().add(AddNote(note));
    context.pop();
  }

  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      create: (context) => sl<NotesBloc>(),
      child: BlocConsumer<NotesBloc, NotesState>(
        listener: (context, state) {
          if (state is NotesFailure) {
            ScaffoldMessenger.of(context).showSnackBar(
              SnackBar(content: Text('Error: ${state.error}')),
            );
          }
        },
        builder: (context, state) {
          return Scaffold(
            appBar: AppBar(
              title: const Text('Add Note'),
              actions: [
                // InkWell(
                //   child: const Icon(Icons.check),
                //   onTap: () => _saveNote(context),
                // ),
                PressableButton(
                 child: Container(
                    padding: const EdgeInsets.all(8.0),
                    child: const Icon(Icons.check),
                    decoration:  BoxDecoration(
                      color: Colors.blue,
                      borderRadius: BorderRadius.circular(8.0),
                    ),
                 ),
                 onTap: () => _saveNote(context))
              ],
            ),
            body: SingleChildScrollView(
              padding: const EdgeInsets.all(16.0),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  TextField(
                    controller: _titleController,
                    style: Theme.of(context).textTheme.headlineSmall,
                    decoration: const InputDecoration(
                      hintText: 'Title',
                      border: InputBorder.none,
                    ),
                  ),
                  const SizedBox(height: 8),
                  TextField(
                    controller: _contentController,
                    maxLines: null,
                    decoration: const InputDecoration(
                      hintText: 'Note content',
                      border: InputBorder.none,
                    ),
                  ),
                  const SizedBox(height: 16),
                  const Divider(),
                  const Text('Tasks', style: TextStyle(fontWeight: FontWeight.bold)),
                  ListView.builder(
                    shrinkWrap: true,
                    physics: const NeverScrollableScrollPhysics(),
                    itemCount: _tasks.length,
                    itemBuilder: (context, index) {
                      final task = _tasks[index];
                      return ListTile(
                        contentPadding: EdgeInsets.zero,
                        leading: const Icon(Icons.check_box_outline_blank),
                        title: Text(task.text),
                        trailing: IconButton(
                          icon: const Icon(Icons.close),
                          onPressed: () => _removeTask(index),
                        ),
                      );
                    },
                  ),
                  Wrap(
                       spacing: 8,
                       children: ["work", "personal", "urgent", "Ideas", "church", "Todo"].map((tag) =>
                        ChoiceChip(
                          selected: _selectedTag == tag,
                          onSelected: (selected) {
                            setState(() {
                              _selectedTag = selected ? tag : '';
                            });
                          },
                          label: Text(tag)))
                          .toList(),
                  ),
                  Row(
                    children: [
                      Expanded(
                        child: TextField(
                          controller: _taskController,
                          decoration: const InputDecoration(
                            hintText: 'Add a task...',
                            border: InputBorder.none,
                          ),
                          onSubmitted: (_) => _addTask(),
                        ),
                      ),
                      IconButton(
                        icon: const Icon(Icons.add),
                        onPressed: _addTask,
                      ),
                    ],
                  ),
                ],
              ),
            ),
          );
        },
      ),
    );
  }
}